In [ ]:
import numpy as np
u = np.array([-1, 2, -3])
print(np.abs(u).sum())

6


In [ ]:
import numpy as np
u = np.array([-6,8])
print(np.linalg.norm(u))

10.0


In [ ]:
import numpy as np
u = np.array([-3, -4])
print(np.linalg.norm(u))

5.0


In [ ]:
v1=np.array([1, -1, 1, -1])
v2=np.array([4, -4, 4, -4])
np.dot(v1, v2)
np.inner(v1, v2)

16

Q1. 본격적으로 Numpy와 친해지기 위해서 다양한 연산을 연습해볼 예정입니다. 무작위의 데이터를 가 진 5x3의 행렬을 가지는 numpy array와 3x2 행렬을 가지는 numpy array를 만든 후 행열곱 연산을 진행해보세요. 

In [ ]:
import numpy as np
arr1 = np.random.rand(5,3)
arr2 = np.random.rand(3,2)

dot=np.dot(arr1, arr2)  # dot 메소드

print(dot, dot.shape)

[[0.5527074  1.18076936]
 [0.72344828 1.59101599]
 [0.41328745 0.66233846]
 [0.50967973 1.31204728]
 [0.45356436 0.98714243]] (5, 2)


Q2. 두번째로는 numpy에서 자주 사용하는 concatenate 연산에 대한 미션을 수행해보겠습니다. 이제 Numpy에서 사용하는 2개의 numpy array가 있을때, 두 numpy array의 concatenate 연산을 구해보세요.  

axis는 0, 1 두개로 연산한 결과를 출력해보세요.
각 데이터가 어떤 형태로 더해지는지 확인해보세요.

In [ ]:
arr1 = np.array([[5, 7], [9, 11]], float)
arr2 = np.array([[2, 4], [6, 8]], float)

concat_1 = np.concatenate((arr1, arr2), axis=0)
concat_2 = np.concatenate((arr1, arr2), axis=1)

print(concat_1)
print(concat_2)

[[ 5.  7.]
 [ 9. 11.]
 [ 2.  4.]
 [ 6.  8.]]
[[ 5.  7.  2.  4.]
 [ 9. 11.  6.  8.]]


Q3. 3번부터 5번까지의 미션는 Numpy를 이용해서 정답값을 예측해보는 linear regression을 구현해 보는 미션입니다. 첫번째 단계로 데이터를 준비해보도록 하겠습니다. 아래와 같이 데이터가 주어져있을 때, 경사하강법을 위한 데이터를 분리해보세요.

주어진 xy 데이터를 이용해서 학습과 정답 데이터를 준비해보세요.

In [ ]:
import numpy as np

xy = np.array([[1., 2., 3., 4., 5., 6.],[10., 20., 30., 40., 50., 60.]])

x_train = xy[0]
y_train = xy[1]

print(x_train, x_train.shape)
print(y_train, y_train.shape)

[1. 2. 3. 4. 5. 6.] (6,)
[10. 20. 30. 40. 50. 60.] (6,)


Q4. 경사 하강법 구현을 위해서 위에서 분리한 x_train 데이터와 계산될 weight, bias 값을 정의해보세요. 여기서 구현한 weight와 bias 는 linear regression 계산을 진행할시 직선의 기울기와 y 절편의 값이 됩니다.

numpy 내의 random 함수를 이용해보세요.

In [ ]:
beta_gd = np.random.rand(1)
bias = np.random.rand(1)

print(beta_gd, bias)

[0.37182568] [0.09345813]


Q5. 이제 최종적으로 linear regression을 경사하강법으로 학습하는 코드를 구현해봅시다. 경사하강법 구현을 위한 학습 Loop를 구현해보세요. 최종적으로 1000회 반복했을 시에 결과를 출력하세요.

단, Error는 차이의 제곱을 이용해서 계산해주세요.
Gradient 값은 우리가 예측하는 각 변수에 대한 미분값입니다.

In [ ]:
import numpy as np

xy = np.array([[1.,2.,3.,4.,5.,6.], [3., 6., 9., 12., 15., 18.]])

x_train = xy[0]
y_train = xy[1]

beta_gd = np.random.rand(1)
bias = np.random.rand(1)

learning_rate = 0.01

for i in range(1000):
  pred = (x_train*beta_gd)+bias
  error = ((pred - y_train)**2).mean()

  gd_w = ((pred - y_train)*2*x_train).mean()
  gd_b = ((pred - y_train)*2).mean()

  beta_gd -= learning_rate*gd_w
  bias-= learning_rate*gd_b

  if i%100==0:
    print('Epoch ({:10d}/1000) error: {:10f}, beta_gd: {:10f}, bias: {:10f}'.format(i, error, beta_gd.item(), bias.item()))

Epoch (         0/1000) error:  76.644878, beta_gd:   1.337869, bias:   0.573308
Epoch (       100/1000) error:   0.077567, beta_gd:   2.852242, bias:   0.632582
Epoch (       200/1000) error:   0.037334, beta_gd:   2.897490, bias:   0.438868
Epoch (       300/1000) error:   0.017970, beta_gd:   2.928881, bias:   0.304474
Epoch (       400/1000) error:   0.008649, beta_gd:   2.950660, bias:   0.211236
Epoch (       500/1000) error:   0.004163, beta_gd:   2.965769, bias:   0.146550
Epoch (       600/1000) error:   0.002004, beta_gd:   2.976251, bias:   0.101672
Epoch (       700/1000) error:   0.000964, beta_gd:   2.983524, bias:   0.070537
Epoch (       800/1000) error:   0.000464, beta_gd:   2.988569, bias:   0.048937
Epoch (       900/1000) error:   0.000223, beta_gd:   2.992070, bias:   0.033951
